{{- if .Values.serviceMesh.route -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "akhq.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "akhq.name" . }}
    helm.sh/chart: {{ include "akhq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
    - {{ .Values.hostname }}
  gateways:
    - {{ include "akhq.fullname" . }}-gateway
  http:
  - route:
    - destination:
        host: {{ include "akhq.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{.Values.service.port}}
{{- end }}
